### ISSUE TITLE
Mathjax Not Rendering

### ISSUE THREAD

**Issue by Alekseyyy** [jamiemcg/Remarkable#160]
Hey there! For some reason, I can't get MathJax text to render (I highlighted an example in the screenshot below). Tried to do an 'apt purge remarkable' and a 'dpkg -i remarkable.deb' but it doesn't seem to work. Can anyone help me solve this, thanks ^_^
![remarkable-not-rendering-mathjax](https://cloud.githubusercontent.com/assets/16161874/25645549/1c0c1ce4-2f7d-11e7-9e21-bfd75dd7a182.png)

**Comment by aphirst** [comment]
I'm experiencing the same issue. Specifically, inline text ($math here$) does not render, but $$goes on a new line$$ does. I'm an Arch user so it's possible that the issue is due to some updated library, but neither do I keep logs of this, nor does Remarkable output anything to the terminal to suggest that there's anything wrong.

**Comment by aphirst** [comment]
@mathmare Does it at least work for you when you $$goes on its own line$$ expressions?

**Comment by aphirst** [comment]
I think I know what's going on here.

https://github.com/jamiemcg/Remarkable/blob/master/remarkable/RemarkableWindow.py#L87
Here is a reference to a MathJax URL which presumably pertains to the rendering of these inline statements, the URL being:
https://cdn.mathjax.org/mathjax/latest/MathJax.js

However if one visits that URL, and reads what's visible there, one notices this line:
```js
    console.warn('WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.')
```
I think that says it all. Remarkable needs to be updated in accordance with the advice visible on that final page, which is basically either to use a MathJax instance from a different CDN provider, or instead to use MathJax locally.

**Comment by aphirst** [comment]
I just tested whether simply changing the URL on that line to one of the new MathJax CDNs fixes this issue, and it seems that it does, so that can be considered a workaround for now. However, I'm kind of surprised that the Internet is involved at all in this process - I would have expected this to all be done locally. Is there some reason for this, @jamiemcg ?

**Comment by mathmare** [comment]
oh yeah I fixed it now, thanks!

**Comment by emilhe** [comment]
I am experiencing the same issue. How did you, @mathmare , apply this fix? Did you build from sources or did you path your local installation? In any case, could you elaborate on the process and/or provide links to relevant documentation?

**Comment by aphirst** [comment]
@emilhe Exactly right, that's what I did locally while waiting for an upstream solution (for example, the simple fix in my PR). I've still not tested whether you can also "easily" point to a local MathJax installation... Maybe I will get around to that when I have some more time.

**Comment by JIWW** [comment]
@emilhe Yeah,it works when I replace URL to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML` in the https://github.com/jamiemcg/Remarkable/blob/master/remarkable/RemarkableWindow.py#L87
file in lines 87.

**Comment by xspkwy** [comment]
@JIWW I have changed the original URL `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML` to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML`, but when I restart remarkable, it doesn't work.
Should I also change the first URL  in lines 87 in the file or something else?
Thanks!

**Comment by JIWW** [comment]
@xspkwy Does it work now?You can try to change the url in the file on line 87 on your computer.

**Comment by xspkwy** [comment]
@JIWW I'm sorry but it didn't work, and I don't know why.
I changed line87 from
`self.default_html_end = '<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script><script>hljs.initHighlightingOnLoad();</script><script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><script type="text/javascript">MathJax.Hub.Config({"showProcessingMessages" : false,"messageStyle" : "none","tex2jax": { inlineMath: [ [ "$", "$" ] ] }});</script></body></html>'`
to
`self.default_html_end = '<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script><script>hljs.initHighlightingOnLoad();</script><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script><script type="text/javascript">MathJax.Hub.Config({"showProcessingMessages" : false,"messageStyle" : "none","tex2jax": { inlineMath: [ [ "$", "$" ] ] }});</script></body></html>'`
was there anything wrong?

**Comment by JIWW** [comment]
@xspkwy In my system,the file is in "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py".Did you modify it?

**Comment by Dubrzr** [comment]
If you are using cloudflare, disable the "Rocket Loader" Speed option.

**Comment by eciii** [comment]
Please note that this might not be the actual solution of the problem. The real problem here is that the inline configuration of MathJax is being defined **after** the loading of the MathJax file via CDN. The MathJax documentation explicitly states that the inline configuration should be defined **before** the loading of the MathJax file: see https://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options. I guess the problem started to appear because after the shut down of the old CDN the MathJax library takes more time to load and thus the inline configuration was never read.

On the other hand just writing the inline configuration before the script tag that loads the MathJax file but leaving it as it is right now will throw a javascript error because the MathJax object is not yet defined. It is necessary to define the configuration in the global window object as explained here: https://docs.mathjax.org/en/latest/configuration.html#using-plain-javascript.

All in all, the infamous line 87 in the RemarkableWindow.py file should read:
~~~
self.default_html_end = '<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script><script>hljs.initHighlightingOnLoad();</script><script type="text/javascript">window.MathJax = {"showProcessingMessages" : false,"messageStyle" : "none", "tex2jax": {"inlineMath": [ ["$","$"] ]}};</script><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script></body></html>'
~~~
were a decision has to be made on wether a fixed version of MathJax is going to be used (in this case version 2.7.4) or just the latest version.

**Comment by csbenz** [comment]
I'm on Lubuntu 17.10 and replacing the line 87 doesn't work. Remarkable doesn't launch anymore after changing the line.

**Comment by eciii** [comment]
I have the exact same line that I posted before and I'm also running Remarkable v. 1.87 but on a Debian stretch machine. It works as expected. Have in mind that you should paste the above line leaving 8 blank spaces at the beginning in order to have the same indentation as the surrounding lines. If that's not the problem I guess the problem should be somewhere else...

**Comment by csbenz** [comment]
@eciii I had left a tab at the beginning of the line instead of 8 lines. Problem solved! Thank you.

**Comment by jacksonloper** [comment]
is this still an issue?  i'm certainly still experiencing it?  confused about what the solution is.

**Comment by johnblommers** [comment]
Remarkable 1.8.7 installed via Snap won't render either inline or display LaTeX formulas on my Ubuntu 19.10 system.

**Comment by eindiran** [comment]
I was still having the issue where inline MathJax expressions wouldn't render with the 1.87 version of the `.deb` package on Ubuntu 18.04; running the version in `master` via `run.sh`, the problem is fixed.

**Comment by Qik000** [comment]
Can confirm this issue on: Ubuntu 18.04.4 LTS and Kubuntu 19.10

**Comment by megodoonch** [comment]
This is still a problem for me on Ubuntu 20.04.2 LTS, running Remarkable version 1.87 (latest version).

**Comment by jaghili** [comment]
Had the same problem with Remarkable 1.87 installed on Arch. I fixed it by replacing `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML` with `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML` in the file  `/usr/lib/python3.10/site-packages/remarkable/RemarkableWindow.py` around line 40.
